### ISSUE TITLE
NER - caught in the middle of an entity, starting with "I-" instead of "B-"

### ISSUE THREAD

**Issue by ghnp5** [deeppavlov/DeepPavlov#1699]
Hi,

This relates to https://github.com/deeppavlov/DeepPavlov/pull/1657
Model `ner_mult_long_demo`

There are several text inputs that return tags/labels that start with "I-" rather than "B-".

Example:

> This is a public service announcement.

This returns:

```
[[["This","is","a","public","service","announcement","."],["O","O","O","O","I-EVENT_NAME","I-EVENT_NAME","O"]]]
```

See how there's no `B-EVENT_NAME`.

---

docker-compose.yml:

```
  ner:
    container_name: ner
    image: deeppavlov/deeppavlov
    environment:
      - CONFIG=ner_mult_long_demo
    restart: always
    volumes:
      - ./deeppavlov/ner_mult_long_demo.json:/usr/local/lib/python3.10/site-packages/deeppavlov/configs/classifiers/ner_mult_long_demo.json
      - ./deeppavlov/sentence_delimiter.py:/usr/local/lib/python3.10/site-packages/deeppavlov/models/tokenizers/sentence_delimiter.py
      - ./deeppavlov/pysbd.txt:/usr/local/lib/python3.10/site-packages/deeppavlov/requirements/pysbd.txt
      - ./deeppavlov/registry.json:/usr/local/lib/python3.10/site-packages/deeppavlov/core/common/registry.json
      - ./deeppavlov/requirements_registry.json:/usr/local/lib/python3.10/site-packages/deeppavlov/core/common/requirements_registry.json
      - ./data:/root/.deeppavlov
      - ./venv:/venv
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/local/bin/python3.10 -m pip install pysbd==0.3.4
        python -m deeppavlov riseapi ner_mult_long_demo -p 5000 -d
```

This doesn't happen in the demo of the website, nor if I use the model `ner_demo_mdeberta_address`
